on:
  push:

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get Release Version
        id: get_version
        run: |
          VERSION=$(./gradlew currentVersion -q -Prelease.quiet)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          ls -lha build/libs/
      - name: Extract Tag Name
        id: tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v4.0.13-env-vars
          name: Release v4.0.13-env-vars
          body: Release v4.0.13-env-vars
          files: build/libs/ansible-plugin-v4.0.13.jar
          draft: false
          prerelease: false
